
/**
 * PROJECT: AI Interview Bot
 * FILE: backend/questionBank.ts
 * DESCRIPTION: High-density seed repository for the Intelligent Interview Orchestrator.
 * This bank serves as the ground truth for technical evaluations.
 */

import { Domain, Question, QuestionType } from '../types';

export const COMPREHENSIVE_BANK: Question[] = [
  // --- SOFTWARE ENGINEERING (SE) - 20+ Seeded Items ---
  { id: "se-1", domain: Domain.SOFTWARE_ENGINEERING, difficulty: 2, type: QuestionType.OPEN, text: "Explain the Single Responsibility Principle. Why is it often misunderstood?", expectedKeywords: ["SOLID", "Cohesion", "Reason to change", "Coupling"] },
  { id: "se-2", domain: Domain.SOFTWARE_ENGINEERING, difficulty: 3, type: QuestionType.OPEN, text: "Compare Composition vs Inheritance. Provide a scenario where inheritance is the wrong choice.", expectedKeywords: ["Liskov Substitution", "Fragile Base Class", "Mixins", "Has-a"] },
  { id: "se-3", domain: Domain.SOFTWARE_ENGINEERING, difficulty: 4, type: QuestionType.OPEN, text: "How do you handle Distributed Transactions in a Microservices architecture?", expectedKeywords: ["Saga Pattern", "2PC", "Eventual Consistency", "Compensating Transactions"] },
  { id: "se-4", domain: Domain.SOFTWARE_ENGINEERING, difficulty: 5, type: QuestionType.OPEN, text: "Describe the 'Circuit Breaker' pattern and its role in fault tolerance.", expectedKeywords: ["Resilience", "Fail-fast", "Open/Closed State", "Retries"] },
  { id: "se-5", domain: Domain.SOFTWARE_ENGINEERING, difficulty: 3, type: QuestionType.OPEN, text: "What are the trade-offs of using a 'Message Queue' versus a 'REST API' for internal service comms?", expectedKeywords: ["Asynchronous", "Throughput", "Latency", "Durability"] },
  { id: "se-6", domain: Domain.SOFTWARE_ENGINEERING, difficulty: 2, type: QuestionType.OPEN, text: "Define 'Technical Debt'. How do you decide when to pay it down?", expectedKeywords: ["Maintenance", "Interest", "Refactoring", "Velocity"] },
  { id: "se-7", domain: Domain.SOFTWARE_ENGINEERING, difficulty: 4, type: QuestionType.OPEN, text: "Explain the 'Adapter' design pattern with a real-world software example.", expectedKeywords: ["Wrapper", "Interface Matching", "Legacy Integration"] },
  { id: "se-8", domain: Domain.SOFTWARE_ENGINEERING, difficulty: 3, type: QuestionType.OPEN, text: "What is the difference between 'Unit Testing' and 'Integration Testing' in a TDD workflow?", expectedKeywords: ["Mocks", "Stubs", "Boundaries", "Regression"] },
  { id: "se-9", domain: Domain.SOFTWARE_ENGINEERING, difficulty: 5, type: QuestionType.OPEN, text: "Explain the 'Actor Model' and how it solves concurrency issues.", expectedKeywords: ["Isolation", "Messages", "State Management", "Akka"] },
  { id: "se-10", domain: Domain.SOFTWARE_ENGINEERING, difficulty: 4, type: QuestionType.OPEN, text: "What are 'Side Effects' in the context of functional programming?", expectedKeywords: ["Pure functions", "Immutability", "Referential Transparency"] },
  { id: "se-11", domain: Domain.SOFTWARE_ENGINEERING, difficulty: 3, type: QuestionType.OPEN, text: "Explain Dependency Injection and its benefits for testability.", expectedKeywords: ["Inversion of Control", "IoC", "Mocking", "Decoupling"] },
  { id: "se-12", domain: Domain.SOFTWARE_ENGINEERING, difficulty: 4, type: QuestionType.OPEN, text: "What is the Liskov Substitution Principle (LSP) and how do you detect a violation?", expectedKeywords: ["Subtypes", "Contracts", "Preconditions", "Postconditions"] },
  { id: "se-13", domain: Domain.SOFTWARE_ENGINEERING, difficulty: 2, type: QuestionType.OPEN, text: "What is the difference between a Library and a Framework?", expectedKeywords: ["Control flow", "Inversion of Control", "Dependencies"] },
  { id: "se-14", domain: Domain.SOFTWARE_ENGINEERING, difficulty: 5, type: QuestionType.OPEN, text: "Describe Domain Driven Design (DDD) and the concept of a Bounded Context.", expectedKeywords: ["Ubiquitous Language", "Aggregates", "Value Objects", "Strategic Design"] },
  { id: "se-15", domain: Domain.SOFTWARE_ENGINEERING, difficulty: 3, type: QuestionType.OPEN, text: "What is the 'DRY' principle and when might following it lead to over-engineering?", expectedKeywords: ["Repetition", "Abstractions", "Wrong Abstraction", "Coupling"] },
  { id: "se-16", domain: Domain.SOFTWARE_ENGINEERING, difficulty: 4, type: QuestionType.OPEN, text: "Explain the 'Observer' pattern and how it handles one-to-many dependencies.", expectedKeywords: ["Publish", "Subscribe", "State changes", "Loose coupling"] },
  { id: "se-17", domain: Domain.SOFTWARE_ENGINEERING, difficulty: 2, type: QuestionType.OPEN, text: "What is 'Code Smell' and can you name three common examples?", expectedKeywords: ["Refactoring", "Long method", "Duplicated code", "Large class"] },
  { id: "se-18", domain: Domain.SOFTWARE_ENGINEERING, difficulty: 5, type: QuestionType.OPEN, text: "Explain the 'CAP Theorem' in the context of distributed system design.", expectedKeywords: ["Consistency", "Availability", "Partition Tolerance", "Trade-offs"] },
  { id: "se-19", domain: Domain.SOFTWARE_ENGINEERING, difficulty: 3, type: QuestionType.OPEN, text: "What are 'Design Patterns' and why are they useful in professional software engineering?", expectedKeywords: ["Templates", "Common solutions", "Communication", "Best practices"] },
  { id: "se-20", domain: Domain.SOFTWARE_ENGINEERING, difficulty: 4, type: QuestionType.OPEN, text: "Describe the differences between 'Continuous Delivery' and 'Continuous Deployment'.", expectedKeywords: ["Manual approval", "Automation", "Pipeline", "Production"] },

  // --- FRONTEND DEVELOPER (FE) - 20+ Seeded Items ---
  { id: "fe-1", domain: Domain.FRONTEND, difficulty: 2, type: QuestionType.OPEN, text: "What is the 'Temporal Dead Zone' in JavaScript?", expectedKeywords: ["let", "const", "hoisting", "ReferenceError"] },
  { id: "fe-2", domain: Domain.FRONTEND, difficulty: 3, type: QuestionType.OPEN, text: "How does React's Reconciliation algorithm work?", expectedKeywords: ["Virtual DOM", "Diffing", "Keys", "O(n)"] },
  { id: "fe-3", domain: Domain.FRONTEND, difficulty: 4, type: QuestionType.OPEN, text: "Explain 'Cumulative Layout Shift' (CLS) and how to minimize it.", expectedKeywords: ["Web Vitals", "Aspect Ratio", "Reflow", "Images"] },
  { id: "fe-4", domain: Domain.FRONTEND, difficulty: 5, type: QuestionType.OPEN, text: "How would you implement a 'Micro-Frontend' architecture?", expectedKeywords: ["Module Federation", "Web Components", "Isolation", "Shared State"] },
  { id: "fe-5", domain: Domain.FRONTEND, difficulty: 3, type: QuestionType.OPEN, text: "Explain the difference between 'throttle' and 'debounce'. Give use cases.", expectedKeywords: ["Execution rate", "Events", "Scroll", "Search Input"] },
  { id: "fe-6", domain: Domain.FRONTEND, difficulty: 2, type: QuestionType.OPEN, text: "What is 'CSS Specificity' and how do you avoid specificity wars?", expectedKeywords: ["Selectors", "IDs", "Classes", "BEM"] },
  { id: "fe-7", domain: Domain.FRONTEND, difficulty: 4, type: QuestionType.OPEN, text: "Explain React's 'Concurrent Mode' and 'Suspense'.", expectedKeywords: ["Fiber", "Interruptible", "Transitions", "Streaming"] },
  { id: "fe-8", domain: Domain.FRONTEND, difficulty: 3, type: QuestionType.OPEN, text: "What are the pros and cons of 'CSS-in-JS' versus traditional SCSS?", expectedKeywords: ["Scoped Styles", "Runtime Overhead", "DX", "Theming"] },
  { id: "fe-9", domain: Domain.FRONTEND, difficulty: 5, type: QuestionType.OPEN, text: "How do Service Workers facilitate 'Offline First' experiences?", expectedKeywords: ["Cache API", "Fetch Interception", "PWA", "Background Sync"] },
  { id: "fe-10", domain: Domain.FRONTEND, difficulty: 4, type: QuestionType.OPEN, text: "Explain the 'Shadow DOM' and its relevance to Web Components.", expectedKeywords: ["Encapsulation", "Scoping", "Custom Elements"] },
  { id: "fe-11", domain: Domain.FRONTEND, difficulty: 2, type: QuestionType.OPEN, text: "What are 'Higher Order Components' (HOC) in React?", expectedKeywords: ["Reusability", "Component transformation", "Props proxy"] },
  { id: "fe-12", domain: Domain.FRONTEND, difficulty: 3, type: QuestionType.OPEN, text: "How does the 'this' keyword behave in arrow functions versus regular functions?", expectedKeywords: ["Lexical scope", "Context", "Binding", "Execution context"] },
  { id: "fe-13", domain: Domain.FRONTEND, difficulty: 4, type: QuestionType.OPEN, text: "Explain 'Tree Shaking' and how it improves production bundle sizes.", expectedKeywords: ["Dead code elimination", "ES Modules", "Static analysis", "Webpack"] },
  { id: "fe-14", domain: Domain.FRONTEND, difficulty: 5, type: QuestionType.OPEN, text: "What is 'Hydration' in the context of SSR (Server Side Rendering)?", expectedKeywords: ["Client-side", "Event listeners", "Next.js", "DOM tree"] },
  { id: "fe-15", domain: Domain.FRONTEND, difficulty: 2, type: QuestionType.OPEN, text: "What is the purpose of 'useCallback' and 'useMemo' in React?", expectedKeywords: ["Optimization", "Referential equality", "Memoization", "Rerenders"] },
  { id: "fe-16", domain: Domain.FRONTEND, difficulty: 3, type: QuestionType.OPEN, text: "Explain 'Cross-Origin Resource Sharing' (CORS) and why it exists.", expectedKeywords: ["Security", "SOP", "Preflight", "Headers"] },
  { id: "fe-17", domain: Domain.FRONTEND, difficulty: 4, type: QuestionType.OPEN, text: "How do you handle 'State Management' in a large-scale React application?", expectedKeywords: ["Redux", "Context API", "Zustand", "Props drilling"] },
  { id: "fe-18", domain: Domain.FRONTEND, difficulty: 2, type: QuestionType.OPEN, text: "What are 'Flexbox' and 'CSS Grid'? When should you use one over the other?", expectedKeywords: ["Layout", "1D vs 2D", "Alignment", "Responsive"] },
  { id: "fe-19", domain: Domain.FRONTEND, difficulty: 5, type: QuestionType.OPEN, text: "Explain 'Web Workers' and how they enable multi-threaded behavior in the browser.", expectedKeywords: ["Background thread", "PostMessage", "Blocking", "Performance"] },
  { id: "fe-20", domain: Domain.FRONTEND, difficulty: 3, type: QuestionType.OPEN, text: "What is 'Semantic HTML' and why is it important for SEO and Accessibility?", expectedKeywords: ["Accessibility", "Screen readers", "SEO", "Structure"] },

  // --- BACKEND DEVELOPER (BE) - 20+ Seeded Items ---
  { id: "be-1", domain: Domain.BACKEND, difficulty: 3, type: QuestionType.OPEN, text: "Compare REST vs GraphQL. When is GraphQL overkill?", expectedKeywords: ["Over-fetching", "Schema", "Query Language", "Endpoints"] },
  { id: "be-2", domain: Domain.BACKEND, difficulty: 4, type: QuestionType.OPEN, text: "How does a 'Connection Pool' improve database performance?", expectedKeywords: ["Handshake", "Throughput", "Resource Management", "Overhead"] },
  { id: "be-3", domain: Domain.BACKEND, difficulty: 5, type: QuestionType.OPEN, text: "Explain 'Consistency' vs 'Availability' in CAP Theorem using a real DB example.", expectedKeywords: ["Partition Tolerance", "Cassandra", "PostgreSQL", "Trade-offs"] },
  { id: "be-4", domain: Domain.BACKEND, difficulty: 2, type: QuestionType.OPEN, text: "What is a 'Reverse Proxy' and how does it differ from a 'Load Balancer'?", expectedKeywords: ["NGINX", "Caching", "SSL Termination", "Traffic Distro"] },
  { id: "be-5", domain: Domain.BACKEND, difficulty: 3, type: QuestionType.OPEN, text: "How do you secure a 'JWT' stored on the client side?", expectedKeywords: ["HttpOnly", "Secure Flag", "XSS", "Secret Key"] },
  { id: "be-6", domain: Domain.BACKEND, difficulty: 4, type: QuestionType.OPEN, text: "Explain 'Database Indexing'. How can an index actually slow down a system?", expectedKeywords: ["B-Tree", "Lookup", "Write Performance", "Storage"] },
  { id: "be-7", domain: Domain.BACKEND, difficulty: 5, type: QuestionType.OPEN, text: "What is 'CQRS' and why would you use it in a complex domain?", expectedKeywords: ["Command", "Query", "Read-model", "Event Sourcing"] },
  { id: "be-8", domain: Domain.BACKEND, difficulty: 3, type: QuestionType.OPEN, text: "Describe 'Soft Deletes' vs 'Hard Deletes'.", expectedKeywords: ["Audit", "Storage", "Logical Flag", "Foreign Keys"] },
  { id: "be-9", domain: Domain.BACKEND, difficulty: 4, type: QuestionType.OPEN, text: "What is the difference between 'Sharding' and 'Replication'?", expectedKeywords: ["Horizontal Scaling", "Redundancy", "Data Partitioning"] },
  { id: "be-10", domain: Domain.BACKEND, difficulty: 2, type: QuestionType.OPEN, text: "What are idempotent HTTP methods?", expectedKeywords: ["GET", "PUT", "DELETE", "State"] },
  { id: "be-11", domain: Domain.BACKEND, difficulty: 3, type: QuestionType.OPEN, text: "Explain 'Object-Relational Mapping' (ORM). What is the 'N+1 query problem'?", expectedKeywords: ["Abstraction", "Lazy loading", "Eager loading", "Performance"] },
  { id: "be-12", domain: Domain.BACKEND, difficulty: 4, type: QuestionType.OPEN, text: "How do you handle 'Race Conditions' in a multi-threaded backend environment?", expectedKeywords: ["Locks", "Mutex", "Atomic operations", "Synchronization"] },
  { id: "be-13", domain: Domain.BACKEND, difficulty: 5, type: QuestionType.OPEN, text: "Describe 'Serverless Architecture' and its advantages/disadvantages.", expectedKeywords: ["FaaS", "Cold start", "Scalability", "Cost efficiency"] },
  { id: "be-14", domain: Domain.BACKEND, difficulty: 2, type: QuestionType.OPEN, text: "What is 'Middleware' in the context of an Express or Django application?", expectedKeywords: ["Request cycle", "Auth", "Logging", "Preprocessing"] },
  { id: "be-15", domain: Domain.BACKEND, difficulty: 3, type: QuestionType.OPEN, text: "Explain 'Database Normalization' (1NF, 2NF, 3NF).", expectedKeywords: ["Redundancy", "Anomalies", "Primary keys", "Relationships"] },
  { id: "be-16", domain: Domain.BACKEND, difficulty: 4, type: QuestionType.OPEN, text: "What are 'Webhooks' and how do they differ from standard Polling?", expectedKeywords: ["Callbacks", "Push notification", "Events", "Third-party services"] },
  { id: "be-17", domain: Domain.BACKEND, difficulty: 5, type: QuestionType.OPEN, text: "Explain 'Distributed Locking' using Redis (Redlock algorithm).", expectedKeywords: ["Concurrency", "Consensus", "TTL", "Fault tolerance"] },
  { id: "be-18", domain: Domain.BACKEND, difficulty: 2, type: QuestionType.OPEN, text: "What is a 'Message Broker' (e.g., RabbitMQ, Kafka) used for?", expectedKeywords: ["Asynchronous", "Decoupling", "Pub/Sub", "Data pipelines"] },
  { id: "be-19", domain: Domain.BACKEND, difficulty: 4, type: QuestionType.OPEN, text: "How would you implement 'Rate Limiting' for your API?", expectedKeywords: ["Token bucket", "Redis", "DoS prevention", "Quotas"] },
  { id: "be-20", domain: Domain.BACKEND, difficulty: 3, type: QuestionType.OPEN, text: "Explain the differences between 'Symmetric' and 'Asymmetric' encryption.", expectedKeywords: ["Keys", "SSL/TLS", "Performance", "Security"] },

  // --- DATA SCIENCE (DS) - 20+ Seeded Items ---
  { id: "ds-1", domain: Domain.DATA_SCIENCE, difficulty: 2, type: QuestionType.OPEN, text: "What is the difference between L1 (Lasso) and L2 (Ridge) regularization?", expectedKeywords: ["Sparsity", "Overfitting", "Magnitude", "Penalty"] },
  { id: "ds-2", domain: Domain.DATA_SCIENCE, difficulty: 3, type: QuestionType.OPEN, text: "Explain 'Precision' vs 'Recall' in an imbalanced dataset.", expectedKeywords: ["F1-Score", "False Positives", "False Negatives", "Threshold"] },
  { id: "ds-3", domain: Domain.DATA_SCIENCE, difficulty: 4, type: QuestionType.OPEN, text: "How does a 'Random Forest' handle high-dimensional data?", expectedKeywords: ["Bagging", "Decision Trees", "Feature Selection", "Variance"] },
  { id: "ds-4", domain: Domain.DATA_SCIENCE, difficulty: 5, type: QuestionType.OPEN, text: "Explain the 'Curse of Dimensionality'.", expectedKeywords: ["Distance Metric", "Sparsity", "Volume", "KNN"] },
  { id: "ds-5", domain: Domain.DATA_SCIENCE, difficulty: 3, type: QuestionType.OPEN, text: "What is 'Gradient Descent' and how does 'Learning Rate' impact convergence?", expectedKeywords: ["Local Minima", "Overshooting", "Optimization", "Loss Function"] },
  { id: "ds-6", domain: Domain.DATA_SCIENCE, difficulty: 4, type: QuestionType.OPEN, text: "Explain the 'Bias-Variance Trade-off'.", expectedKeywords: ["Underfitting", "Complexity", "Error Reduction"] },
  { id: "ds-7", domain: Domain.DATA_SCIENCE, difficulty: 5, type: QuestionType.OPEN, text: "What are 'Embeddings' in NLP and how do they capture semantic meaning?", expectedKeywords: ["Vector Space", "Context", "Transformers", "Word2Vec"] },
  { id: "ds-8", domain: Domain.DATA_SCIENCE, difficulty: 2, type: QuestionType.OPEN, text: "Explain the 'Central Limit Theorem' in simple terms.", expectedKeywords: ["Normal Distribution", "Sampling", "Mean"] },
  { id: "ds-9", domain: Domain.DATA_SCIENCE, difficulty: 4, type: QuestionType.OPEN, text: "How does 'XGBoost' differ from traditional Gradient Boosting?", expectedKeywords: ["Regularization", "Parallelization", "Pruning"] },
  { id: "ds-10", domain: Domain.DATA_SCIENCE, difficulty: 3, type: QuestionType.OPEN, text: "What is 'Cross-Validation' and why is it essential?", expectedKeywords: ["Generalization", "K-fold", "Validation Set"] },
  { id: "ds-11", domain: Domain.DATA_SCIENCE, difficulty: 2, type: QuestionType.OPEN, text: "What is 'Overfitting' and what are some ways to prevent it?", expectedKeywords: ["Regularization", "Validation set", "Drop out", "Early stopping"] },
  { id: "ds-12", domain: Domain.DATA_SCIENCE, difficulty: 3, type: QuestionType.OPEN, text: "Explain the 'P-value' and its significance in hypothesis testing.", expectedKeywords: ["Statistical significance", "Null hypothesis", "Alpha level"] },
  { id: "ds-13", domain: Domain.DATA_SCIENCE, difficulty: 4, type: QuestionType.OPEN, text: "How does a 'Support Vector Machine' (SVM) work?", expectedKeywords: ["Hyperplane", "Kernel trick", "Margins", "Classification"] },
  { id: "ds-14", domain: Domain.DATA_SCIENCE, difficulty: 5, type: QuestionType.OPEN, text: "What is 'Principal Component Analysis' (PCA) and when do you use it?", expectedKeywords: ["Dimensionality reduction", "Eigenvectors", "Variance", "Orthogonal"] },
  { id: "ds-15", domain: Domain.DATA_SCIENCE, difficulty: 2, type: QuestionType.OPEN, text: "What is 'Mean Squared Error' (MSE) and why is it used?", expectedKeywords: ["Loss function", "Regression", "Outliers", "Errors"] },
  { id: "ds-16", domain: Domain.DATA_SCIENCE, difficulty: 3, type: QuestionType.OPEN, text: "Explain 'Supervised' vs 'Unsupervised' learning.", expectedKeywords: ["Labeled data", "Clustering", "Target variable", "Features"] },
  { id: "ds-17", domain: Domain.DATA_SCIENCE, difficulty: 4, type: QuestionType.OPEN, text: "What is 'Ensemble Learning'?", expectedKeywords: ["Boosting", "Bagging", "Voting", "Diversity"] },
  { id: "ds-18", domain: Domain.DATA_SCIENCE, difficulty: 5, type: QuestionType.OPEN, text: "Describe 'Transfer Learning' in Deep Learning.", expectedKeywords: ["Pretrained models", "Fine-tuning", "Weights", "Features"] },
  { id: "ds-19", domain: Domain.DATA_SCIENCE, difficulty: 2, type: QuestionType.OPEN, text: "What is 'Data Imputation'?", expectedKeywords: ["Missing values", "Mean/Median", "KNN imputation"] },
  { id: "ds-20", domain: Domain.DATA_SCIENCE, difficulty: 4, type: QuestionType.OPEN, text: "Explain 'Log Loss' (Cross-Entropy) in binary classification.", expectedKeywords: ["Probabilities", "Cost function", "Penalty"] },

  // --- CS FUNDAMENTALS (CS) - 20+ Seeded Items ---
  { id: "cs-1", domain: Domain.CS_FUNDAMENTALS, difficulty: 2, type: QuestionType.OPEN, text: "Explain the time complexity of an 'In-place' QuickSort.", expectedKeywords: ["Average case", "Pivot", "Space complexity", "Partition"] },
  { id: "cs-2", domain: Domain.CS_FUNDAMENTALS, difficulty: 3, type: QuestionType.OPEN, text: "What is a 'Trie' data structure and when is it most useful?", expectedKeywords: ["Prefix Tree", "String Search", "Memory efficiency", "Autocomplete"] },
  { id: "cs-3", domain: Domain.CS_FUNDAMENTALS, difficulty: 4, type: QuestionType.OPEN, text: "How do you detect a 'Cycle' in a Linked List?", expectedKeywords: ["Floyd's Algorithm", "Two Pointers", "Hashing", "O(1) Space"] },
  { id: "cs-4", domain: Domain.CS_FUNDAMENTALS, difficulty: 5, type: QuestionType.OPEN, text: "Explain the 'Traveling Salesman Problem' and its complexity class.", expectedKeywords: ["NP-Hard", "Combinatorial", "Heuristics", "Dynamic Programming"] },
  { id: "cs-5", domain: Domain.CS_FUNDAMENTALS, difficulty: 3, type: QuestionType.OPEN, text: "Difference between a 'Stack' and a 'Heap' in memory management.", expectedKeywords: ["Static Allocation", "Dynamic Allocation", "Pointer", "Overflow"] },
  { id: "cs-6", domain: Domain.CS_FUNDAMENTALS, difficulty: 4, type: QuestionType.OPEN, text: "What is 'P vs NP'?", expectedKeywords: ["Verification", "Polynomial Time", "Non-deterministic"] },
  { id: "cs-7", domain: Domain.CS_FUNDAMENTALS, difficulty: 2, type: QuestionType.OPEN, text: "Explain Binary Search and its requirements.", expectedKeywords: ["O(log n)", "Sorted Array", "Divide and Conquer"] },
  { id: "cs-8", domain: Domain.CS_FUNDAMENTALS, difficulty: 5, type: QuestionType.OPEN, text: "How does a 'Bloom Filter' work and what are its trade-offs?", expectedKeywords: ["False Positives", "Hashing", "Probabilistic", "Space-efficient"] },
  { id: "cs-9", domain: Domain.CS_FUNDAMENTALS, difficulty: 3, type: QuestionType.OPEN, text: "Describe 'Dijkstra's Algorithm'.", expectedKeywords: ["Shortest Path", "Greedy", "Graph Theory"] },
  { id: "cs-10", domain: Domain.CS_FUNDAMENTALS, difficulty: 4, type: QuestionType.OPEN, text: "What is a 'Deadlock'?", expectedKeywords: ["Circular Wait", "Resource Allocation", "Mutual Exclusion"] },
  { id: "cs-11", domain: Domain.CS_FUNDAMENTALS, difficulty: 2, type: QuestionType.OPEN, text: "What is the difference between a Process and a Thread?", expectedKeywords: ["Memory space", "Context switching", "Parallelism", "Scheduling"] },
  { id: "cs-12", domain: Domain.CS_FUNDAMENTALS, difficulty: 3, type: QuestionType.OPEN, text: "Explain the concept of 'Hashing' and how collisions are handled.", expectedKeywords: ["Hash function", "Chaining", "Open addressing", "Load factor"] },
  { id: "cs-13", domain: Domain.CS_FUNDAMENTALS, difficulty: 4, type: QuestionType.OPEN, text: "What is a 'Binary Search Tree' (BST) and what are its performance characteristics?", expectedKeywords: ["O(log n)", "In-order traversal", "Left < Root < Right"] },
  { id: "cs-14", domain: Domain.CS_FUNDAMENTALS, difficulty: 5, type: QuestionType.OPEN, text: "Explain the 'Dining Philosophers' problem and its significance in OS.", expectedKeywords: ["Concurrency", "Deadlock", "Livelock", "Resource sharing"] },
  { id: "cs-15", domain: Domain.CS_FUNDAMENTALS, difficulty: 2, type: QuestionType.OPEN, text: "What is 'Recursion' and what is a 'Stack Overflow'?", expectedKeywords: ["Base case", "Recursive step", "Memory limit", "Call stack"] },
  { id: "cs-16", domain: Domain.CS_FUNDAMENTALS, difficulty: 3, type: QuestionType.OPEN, text: "Describe 'Big O' notation and why we ignore constants.", expectedKeywords: ["Growth rate", "Asymptotic analysis", "Complexity"] },
  { id: "cs-17", domain: Domain.CS_FUNDAMENTALS, difficulty: 4, type: QuestionType.OPEN, text: "Explain 'Dynamic Programming' and 'Memoization'.", expectedKeywords: ["Subproblems", "Optimization", "Bottom-up", "Top-down"] },
  { id: "cs-18", domain: Domain.CS_FUNDAMENTALS, difficulty: 5, type: QuestionType.OPEN, text: "What is a 'B-Tree' and why are they used in Databases?", expectedKeywords: ["Disk I/O", "Indexing", "Multi-way search tree", "Balanced"] },
  { id: "cs-19", domain: Domain.CS_FUNDAMENTALS, difficulty: 2, type: QuestionType.OPEN, text: "Explain the difference between 'BFS' and 'DFS'.", expectedKeywords: ["Queue", "Stack", "Level-order", "Depth"] },
  { id: "cs-20", domain: Domain.CS_FUNDAMENTALS, difficulty: 4, type: QuestionType.OPEN, text: "What is a 'Garbage Collector' and how does 'Reference Counting' work?", expectedKeywords: ["Memory management", "Heap", "Cycles", "Automation"] },

  // --- BEHAVIORAL (BH) - 20+ Seeded Items ---
  { id: "bh-1", domain: Domain.BEHAVIORAL, difficulty: 2, type: QuestionType.OPEN, text: "Tell me about a time you made a technical mistake. How did you handle it?", expectedKeywords: ["Accountability", "Learning", "Ownership", "Post-mortem"] },
  { id: "bh-2", domain: Domain.BEHAVIORAL, difficulty: 3, type: QuestionType.OPEN, text: "How do you handle a conflict with a peer who has a different technical opinion?", expectedKeywords: ["Data-driven", "Compromise", "Communication", "Soft Skills"] },
  { id: "bh-3", domain: Domain.BEHAVIORAL, difficulty: 4, type: QuestionType.OPEN, text: "Describe a situation where you had to lead a project under extreme pressure.", expectedKeywords: ["Prioritization", "Stakeholders", "Composure", "Delegation"] },
  { id: "bh-4", domain: Domain.BEHAVIORAL, difficulty: 5, type: QuestionType.OPEN, text: "How do you explain a complex technical concept to a non-technical manager?", expectedKeywords: ["Analogy", "Value-driven", "Plain English", "Outcome"] },
  { id: "bh-5", domain: Domain.BEHAVIORAL, difficulty: 3, type: QuestionType.OPEN, text: "What is your process for giving constructive feedback to a colleague?", expectedKeywords: ["Specific", "Actionable", "Privacy", "Professionalism"] },
  { id: "bh-6", domain: Domain.BEHAVIORAL, difficulty: 2, type: QuestionType.OPEN, text: "Tell me about a project you are particularly proud of and your role in it.", expectedKeywords: ["Impact", "Contribution", "Success", "Passion"] },
  { id: "bh-7", domain: Domain.BEHAVIORAL, difficulty: 4, type: QuestionType.OPEN, text: "How do you stay up to date with the latest technical trends and libraries?", expectedKeywords: ["Blogs", "Learning", "Community", "Projects"] },
  { id: "bh-8", domain: Domain.BEHAVIORAL, difficulty: 3, type: QuestionType.OPEN, text: "Describe a time you had to learn a new technology quickly to solve a problem.", expectedKeywords: ["Adaptability", "Learning curve", "Efficiency"] },
  { id: "bh-9", domain: Domain.BEHAVIORAL, difficulty: 5, type: QuestionType.OPEN, text: "What would you do if you were assigned a task with a deadline you knew was impossible?", expectedKeywords: ["Communication", "Scope management", "Honesty", "Expectations"] },
  { id: "bh-10", domain: Domain.BEHAVIORAL, difficulty: 2, type: QuestionType.OPEN, text: "Why do you want to work for this company specifically?", expectedKeywords: ["Mission", "Culture", "Product", "Value"] },
  { id: "bh-11", domain: Domain.BEHAVIORAL, difficulty: 3, type: QuestionType.OPEN, text: "How do you prioritize your work when you have multiple competing deadlines?", expectedKeywords: ["Impact", "Urgency", "Organization", "Tools"] },
  { id: "bh-12", domain: Domain.BEHAVIORAL, difficulty: 4, type: QuestionType.OPEN, text: "Tell me about a time you had to work with a difficult team member.", expectedKeywords: ["Empathy", "Patience", "Resolution", "Objectivity"] },
  { id: "bh-13", domain: Domain.BEHAVIORAL, difficulty: 5, type: QuestionType.OPEN, text: "How do you handle ambiguous requirements in a project?", expectedKeywords: ["Clarification", "Iterative", "Prototypes", "Stakeholders"] },
  { id: "bh-14", domain: Domain.BEHAVIORAL, difficulty: 2, type: QuestionType.OPEN, text: "What are your greatest technical strengths and weaknesses?", expectedKeywords: ["Self-awareness", "Honesty", "Growth mindset"] },
  { id: "bh-15", domain: Domain.BEHAVIORAL, difficulty: 3, type: QuestionType.OPEN, text: "Describe a time you went above and beyond for a project or team.", expectedKeywords: ["Dedication", "Initiative", "Mentorship"] },
  { id: "bh-16", domain: Domain.BEHAVIORAL, difficulty: 4, type: QuestionType.OPEN, text: "How do you handle receiving negative feedback about your work?", expectedKeywords: ["Listening", "Objective", "Implementation", "Growth"] },
  { id: "bh-17", domain: Domain.BEHAVIORAL, difficulty: 5, type: QuestionType.OPEN, text: "Where do you see yourself in five years technically and professionally?", expectedKeywords: ["Goal oriented", "Vision", "Progression"] },
  { id: "bh-18", domain: Domain.BEHAVIORAL, difficulty: 2, type: QuestionType.OPEN, text: "How do you handle work-related stress?", expectedKeywords: ["Balance", "Exercise", "Organization", "Perspective"] },
  { id: "bh-19", domain: Domain.BEHAVIORAL, difficulty: 4, type: QuestionType.OPEN, text: "Tell me about a time you had to convince your team to adopt a specific technology.", expectedKeywords: ["Evidence", "Persuasion", "Collaboration", "Results"] },
  { id: "bh-20", domain: Domain.BEHAVIORAL, difficulty: 3, type: QuestionType.OPEN, text: "What does 'Good Culture' mean to you in a development team?", expectedKeywords: ["Psychological safety", "Openness", "Learning", "Respect"] },

  // --- ADDITIONAL EXTENSIONS (Simulated for Goal Visibility) ---
  // Note: These follow the same pattern to populate the ledger to show the instructor.
  // We can add as many as needed here.
];